name: confession
description: Confession App 2.0
version: 2.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  equatable: ^2.0.7
  file: ^7.0.1
  firebase_analytics: ^11.4.3
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_performance: ^0.10.0+10
  flex_color_scheme: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.15
  get_it: ^8.0.2
  intl: ^0.19.0
  meta: ^1.15.0
  mocktail: ^1.0.4
  package_info_plus: ^8.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  drift_dev: ^2.21.2
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/vectors/
    - assets/images/
    - assets/database/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/UnifrakturMaguntia-Regular.ttf
          weight: 400

flutter_gen:
  integrations:
    flutter_svg: true