// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9hXLZnMilQA01KRBXJxYAnLwAdUZwxU',
    appId: '1:852942704392:web:7362c02f9959ad70ef66bd',
    messagingSenderId: '852942704392',
    projectId: 'confession-flutter',
    authDomain: 'confession-flutter.firebaseapp.com',
    storageBucket: 'confession-flutter.firebasestorage.app',
    measurementId: 'G-QXJJ4JCKH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyc5FHsEC9myFIqvU6Yelv4IZGYS65-sY',
    appId: '1:852942704392:android:1ca3cde992e562f4ef66bd',
    messagingSenderId: '852942704392',
    projectId: 'confession-flutter',
    storageBucket: 'confession-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUMfRKqi3OTTgLcZYUdFOFvoUVX8XZdi4',
    appId: '1:852942704392:ios:f862fec1760d760bef66bd',
    messagingSenderId: '852942704392',
    projectId: 'confession-flutter',
    storageBucket: 'confession-flutter.firebasestorage.app',
    iosClientId: '852942704392-pjfi6kurmqpgvadd6olec015fu96367t.apps.googleusercontent.com',
    iosBundleId: 'com.norvera.confession',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUMfRKqi3OTTgLcZYUdFOFvoUVX8XZdi4',
    appId: '1:852942704392:ios:8af701cecaa92cd4ef66bd',
    messagingSenderId: '852942704392',
    projectId: 'confession-flutter',
    storageBucket: 'confession-flutter.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk9hXLZnMilQA01KRBXJxYAnLwAdUZwxU',
    appId: '1:852942704392:web:57b799c7d227ace3ef66bd',
    messagingSenderId: '852942704392',
    projectId: 'confession-flutter',
    authDomain: 'confession-flutter.firebaseapp.com',
    storageBucket: 'confession-flutter.firebasestorage.app',
    measurementId: 'G-TDGKK2GGL9',
  );
}